const reviews = [
  {
    id: 1,
    userId: 1,
    productId: 1,
    orderId: 1,
    avatar: "T",
    userusername: "Trinh",
    point: 5,
    createAt: "27/5/2023 09:09",
    reviewContent: "Điện thoại rất tốt.",
  },
  {
    id: 2,
    userId: 1,
    productId: 1,
    orderId: 1,
    avatar: "J",
    username: "Jonathan",
    createAt: "20/5/2023 10:50",
    point: 4,
    reviewContent: "sản phẩm dùng ổn.",
  },
  {
    id: 3,
    userId: 1,
    productId: 1,
    orderId: 1,
    avatar: "S",
    username: "Sơn Hải",
    createAt: "28/5/2023 14:08",
    point: 4,
    reviewContent: "Sản phẩm rất tốt.",
  },
  {
    id: 4,
    userId: 1,
    productId: 1,
    orderId: 1,
    avatar: "N",
    username: "Vũ Xuân Nam",
    createAt: "20/4/2023 17:50",
    point: 5,
    reviewContent: "sản phẩm tốt nhân viên nhiệt tình",
  },
  {
    id: 5,
    userId: 1,
    productId: 1,
    orderId: 1,
    avatar: "T",
    username: "Trần Thanh Tiền",
    createAt: "14/4/2023 18:01",
    point: 5,
    reviewContent: "Máy mượt mà đẹp pin Sài được 1 ngày trọn vẹn, nhân viên hỗ trợ nhiệt tình.",
  },
  {
    id: 6,
    userId: 1,
    productId: 1,
    orderId: 1,
    avatar: "D",
    username: "John Dang",
    createAt: "22/3/2023 18:41",
    point: 4.5,
    reviewContent: "Máy mượt mà đẹp pin xài được 1 ngày trọn vẹn.",
  },
  {
    id: 7,
    userId: 1,
    productId: 1,
    orderId: 1,
    avatar: "S",
    username: "Sunny",
    createAt: "20/3/2023 13:11",
    point: 5,
    reviewContent: "nhân viên hỗ trợ nhiệt tình, máy xài ổn.",
  },
  {
    id: 8,
    userId: 1,
    productId: 1,
    orderId: 1,
    avatar: "H",
    username: "Henry Tran",
    createAt: "15/3/2023 15:35",
    point: 3.5,
    reviewContent: "nhân viên tư vấn tốt, máy hiện tại đang xài ổn.",
  },
  {
    id: 9,
    userId: 1,
    productId: 1,
    orderId: 1,
    avatar: "B",
    username: "Brian Nguyen",
    createAt: "10/3/2023 13:35",
    point: 5,
    reviewContent: "nhân viên tư vấn tốt, camera khá ổn.",
  },
  {
    id: 10,
    userId: 1,
    productId: 1,
    orderId: 1,
    avatar: "L",
    username: "Linh Dang",
    createAt: "09/3/2023 09:42",
    point: 4.5,
    reviewContent: "Máy thiết kế đẹp, camera ổn, cảm ứng mượt.",
  },
  {
    id: 11,
    userId: 1,
    productId: 1,
    orderId: 1,
    avatar: "A",
    username: "Andy Linh",
    createAt: "15/3/2023 15:35",
    point: 5,
    reviewContent: "nhân viên tư vấn tốt, máy hiện tại đang xài ổn.",
  },
];

export default reviews;